tudou:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: tudou_take_out
    username: root
    password: ***REMOVED***

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ***REMOVED***
    secret-key-secret: ***REMOVED***
    bucket-name: sky-itcast