tudou:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: tudou_take_out
    username: root
    password: ***REMOVED***

  upload:
    path: /Users/fangtudou/ComputerScience/Tudou-Take-Out/images/